services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: twitch-giveaway
    restart: unless-stopped
#    ports:
#      - "3010:3000"
    volumes:
      - giveaway-data:/app/data
    environment:
      - NODE_ENV=production
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  default:
    external: true
    name: proxy-network

volumes:
  giveaway-data:
    driver: local
